name: cence_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Upgrade FlutterFire packages to latest major versions (aligned)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
