name: cence_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # FlutterFire (aligned latest majors)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0

  # State management (Riverpod)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Local storage & utils
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1

  # UI & tools
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_slidable: ^4.0.0

  # Data classes & JSON
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # App icon generator
  flutter_launcher_icons: ^0.13.1
  
  # Code generation
  build_runner: ^2.4.11
  riverpod_generator: ^2.3.5
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  web: true
  macos: true
  windows: true
  linux: true
  image_path: assets/app_icon/icon.png
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21
