// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzCkvf9ZKwvVICRZVj-BUn5kPNg3l6jQw',
    appId: '1:393031115817:web:e95132b892b0736d2c2838',
    messagingSenderId: '393031115817',
    projectId: 'cenceapp',
    authDomain: 'cenceapp.firebaseapp.com',
    storageBucket: 'cenceapp.firebasestorage.app',
    measurementId: 'G-9KDTNNTK0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo5vMkQMzB8hyNhQAIEkFW_QtDqYTTYrw',
    appId: '1:393031115817:android:9e71cd12d1b5e16f2c2838',
    messagingSenderId: '393031115817',
    projectId: 'cenceapp',
    storageBucket: 'cenceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1LuzfoIseWw73txyd_lD4hhiesxxyZY0',
    appId: '1:393031115817:ios:14fd76b312836e632c2838',
    messagingSenderId: '393031115817',
    projectId: 'cenceapp',
    storageBucket: 'cenceapp.firebasestorage.app',
    iosBundleId: 'com.example.cenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1LuzfoIseWw73txyd_lD4hhiesxxyZY0',
    appId: '1:393031115817:ios:14fd76b312836e632c2838',
    messagingSenderId: '393031115817',
    projectId: 'cenceapp',
    storageBucket: 'cenceapp.firebasestorage.app',
    iosBundleId: 'com.example.cenceApp',
  );

}