// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'web-api-key-placeholder',
    appId: '1:123456789:web:placeholder',
    messagingSenderId: '123456789',
    projectId: 'cence-app-placeholder',
    authDomain: 'cence-app-placeholder.firebaseapp.com',
    storageBucket: 'cence-app-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'android-api-key-placeholder',
    appId: '1:123456789:android:placeholder',
    messagingSenderId: '123456789',
    projectId: 'cence-app-placeholder',
    storageBucket: 'cence-app-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'ios-api-key-placeholder',
    appId: '1:123456789:ios:placeholder',
    messagingSenderId: '123456789',
    projectId: 'cence-app-placeholder',
    storageBucket: 'cence-app-placeholder.appspot.com',
    iosClientId: 'ios-client-id-placeholder',
    iosBundleId: 'com.example.cenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'macos-api-key-placeholder',
    appId: '1:123456789:ios:placeholder',
    messagingSenderId: '123456789',
    projectId: 'cence-app-placeholder',
    storageBucket: 'cence-app-placeholder.appspot.com',
    iosClientId: 'macos-client-id-placeholder',
    iosBundleId: 'com.example.cenceApp',
  );
}